# -*- coding: utf-8 -*-
"""exercicios_20240219.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1HiDtqM84VVy9ipGXRPZ1ZKdH-hlD9d6m
"""

salario = float(input('Entre com o valor do salario: '))
acrescimo = float(input('Valor de incremento: '))
while (salario < 5000):
  salario += acrescimo
  print(f'Salario atualizado {salario:.2f}')

# Faça um programa que peça uma nota, entre zero e dez. Mostre uma mensagem caso o valor seja inválido e continue pedindo até que o usuário informe um valor válido
while True:
  nota = float(input('Entre com nota: '))
  if nota > 0 and nota < 10: break
  print('Valor invalido')

# Faça um programa que calcule o mostre a média aritmética de N notas
contador = int()
soma = float()
qtde = int(input('Digite a qtde de notas:'))
while contador < qtde:
  soma += float(input('Entre com o valor da nota: '))
  contador+=1
print(f'Sua média é: {(soma/qtde)} ')

# Faça um programa que leia um nome de usuário e a sua senha e não aceite a senha igual ao nome do usuário, mostrando uma mensagem de erro e voltando a pedir as informações.
while True:
  usuario = input('Digite o seu login de usuario: ')
  senha   = input('Digite sua senha: ')
  if usuario != senha : break
  print('Senha de usuario nao pode ser igual ao login!')

"""Um funcionário de uma empresa recebe aumento salarial anualmente.
Sabe-se que: Esse funcionário foi contratado em 1995, com salário inicial de R$
1.000,00; Em 1996 recebeu aumento de 1,5% sobre seu salário inicial; A partir de
1997 (inclusive), os aumentos salariais sempre correspondem ao dobro do
percentual do ano anterior. Faça um programa que determine o salário atual desse
funcionário. Após concluir isto, altere o programa permitindo que o usuário digite o
salário inicial do funcionário.
"""

salario = 1000
percentual = 1.5
ano = 1996
salario_reajustado = salario
while ano < 2025:
  reajuste = salario * (percentual/100)
  salario_reajustado += salario + reajuste
  print(ano, salario_reajustado,reajuste,percentual)
  percentual*=2
  ano+=1

"""Faça um programa que leia e valide as seguintes informações:
 Nome: maior que 3 caracteres;
 Idade: entre 0 e 150;
 Salário: maior que zero;
 Sexo: 'f' ou 'm';
 Estado Civil: 's', 'c', 'v', 'd';
"""

while True:
  nome = input('Digite seu nome: ')
  if len(nome)<3:
    print('Nome invalido digite novamente.')
    continue

  idade = int(input('Digite sua idade: '))
  if idade < 0 or idade >150:
    print('idade ivalida.')
    continue

  salario = float(input('Digite seu salario: '))
  if salario < 0 :
    print('salario invalido.')
    continue

  sexo = input('Digite seu sexo (F,M): ')
  if sexo not in ['M','F']:
    print('Sexo invalido.')
    continue

  estado_civil = input('Digite seu estado civil (S,C,V,D): ')
  if estado_civil not in ['S','C','V','D']:
    print('Estado Civil invalido.')
    continue

  break

"""Supondo que a população de um país A seja da ordem de 80000 habitantes com
uma taxa anual de crescimento de 3% e que a população de B seja 200000
habitantes com uma taxa de crescimento de 1.5%. Faça um programa que calcule e
escreva o número de anos necessários para que a população do país A ultrapasse
ou iguale a população do país B, mantidas as taxas de crescimento.
"""

pais_a = 80000
pais_b = 200000
contador = 0
while pais_a < pais_b:
  contador +=1
  pais_a += pais_a * 0.03
  pais_b += pais_b * 0.015

print(f'E nescessario {contador} anos para o pais A ter a mesma populacao do pais B')

# Faça um programa que calcule o fatorial de um número inteiro fornecido pelo usuário. Ex.: 5!=5.4.3.2.1=120

fatorial = int(input('Digite um numero para fatoriar: '))
numero = 0
resultado = 1
while numero < fatorial:
    resultado += (resultado * numero)
    numero +=1
print(f'Fatorial de {fatorial} é ',resultado)

# Faça um programa que solicite ao usuário números indefinidamente até que ele digite 0. Em seguida, o programa deve imprimir a média dos números digitados.

soma = 0.0
contador = 0
numero = 1
while numero != 0:
  numero = float(input('Digite um numero: '))
  soma += numero
  contador +=1

print(f'A qtde de numeros digitados: {contador}, soma dos numeros {soma} e a média é {soma/contador}')

# A série de Fibonacci é formada pela sequência 1,1,2,3,5,8,13,21,34,55,... Faça um programa capaz de gerar a série até o n−ésimo termo.
quantidade = 10
contador = 0
valor1 = 1
valor2 = 1
soma = 0
print(valor1)
print(valor2)
while contador < quantidade:
  soma = valor1 + valor2
  print(soma)
  valor1 = valor2
  valor2 = soma
  contador+=1

"""10. O Sr. Manoel Joaquim expandiu seus negócios para além dos negócios de 1,99 e
agora possui uma loja de conveniências. Faça um programa que implemente uma
caixa registradora rudimentar.
 O programa deverá receber um número desconhecido de valores referentes
aos preços das mercadorias. Um valor zero deve ser informado pelo
operador para indicar o final da compra.
 O programa deve então mostrar o total da compra e perguntar o valor em
dinheiro que o cliente forneceu, para então calcular e mostrar o valor do
troco. Após esta operação, o programa deverá voltar ao ponto inicial, para
registrar a próxima compra.
 A saída deve ser conforme o exemplo abaixo:
 Lojas Tabajara
 Produto 1: R$ 2.20
 Produto 2: R$ 5.80
 Produto 3: R$ 0
 Total: R$ 9.00
 Dinheiro: R$ 20.00
 Troco: R$ 11.00


"""

valor=1.0
soma=0.0
continuar = 'S'
while continuar == 'S':

  while valor!=0:
    produto = input('Digite o nome do produto: ')
    valor = float(input('Digite o preco do produto: '))
    soma += valor
    print(f'{produto} - R$ {valor}')

  pagamento = float(input('Informe o valor de pagamento: '))
  print('Total da compra: ',soma)
  print('Valor em dinheiro: ',pagamento)
  print('Troco:',pagamento-soma)
  continuar = str(input('Deseja continuar?: (S/N)')).upper()

"""11. O cardápio de uma lanchonete é o seguinte:
Especificação Código Preço
 Cachorro Quente 100 R$ 1,20
 Bauru Simples 101 R$ 1,30
 Bauru com ovo 102 R$ 1,50
 Hambúrguer 103 R$ 1,20
 Cheeseburguer 104 R$ 1,30
 Refrigerante 105 R$ 1,00
Faça um programa que leia o código dos itens pedidos e as quantidades desejadas.
Calcule e mostre o valor a ser pago por item (preço * quantidade) e o total geral do
pedido. Considere que o cliente deve informar quando o pedido deve ser encerrado.
"""

codigo = [100,101,102,103,104,105]
produto = ['Cachorro Quente','Bauru Simples','Bauru com ovo','Hambúrguer','Cheeseburguer','Refrigerante']
preco = [1.20,1.30,1.50,1.20,1.30,1.00]
contador = 0
total = 0
finalizar = 'N'

while finalizar != 'S' :
  cod = int(input('Digite o codigo do produto: '))-100
  qtd = int(input('Digite a qtde do produto: '))

  tot_p = preco[cod]*qtd
  total += tot_p
  print(f'Produto {produto[cod]}, Preco: {preco[cod]}, Qtde: {qtd}, total: {tot_p}')
  contador+=1
  finalizar = str(input('\nFinalizar pedido? (S/N): ')).upper()

print(f'\nTotal do pedido é: {total}')

"""12. Em uma eleição presidencial existem quatro candidatos. Os votos são informados
por meio de código.
Os códigos utilizados são:
 1, 2, 3, 4 - Votos para os respectivos candidatos
 (você deve montar a tabela ex: 1 - Jose/ 2- João/etc)
 5 - Voto Nulo
 6 - Voto em Branco
Faça um programa que calcule e mostre:
 O total de votos para cada candidato;
 O total de votos nulos;
 O total de votos em branco;
 A percentagem de votos nulos sobre o total de votos;
 A percentagem de votos em branco sobre o total de votos.
Para finalizar o conjunto de votos tem-se o valor zero.
"""

candidato1 = 'Jose'
candidato2 = 'Joao'
candidato3 = 'Maria'
candidato4 = 'Joaquim'
candidato5 = 'Nulo'
candidato6 = 'Branco'
qtde=0
voto = 999
voto1=0
voto2=0
voto3=0
voto4=0
nulo=0
branco=0
while voto != 0:
  voto = int(input('Digite o codigo do candidato'))
  if voto==1: voto1+=1
  elif voto==2: voto2+=1
  elif voto==3: voto3+=1
  elif voto==4: voto4+=1
  elif voto==5: nulo+=1
  else: branco+=1
  qtde+=1

print('\nQtde de votos:', qtde)
print(f'Candidato {candidato1}, qtde de votos {voto1}')
print(f'Candidato {candidato2}, qtde de votos {voto2}')
print(f'Candidato {candidato3}, qtde de votos {voto3}')
print(f'Candidato {candidato4}, qtde de votos {voto4}')
print(f'Candidato {candidato5}, qtde de votos {nulo}')
print(f'Candidato {candidato6}, qtde de votos {branco}')
print(f'% de nulos sobre o total: {nulo/qtde}')
print(f'% de brancos sobre o total: {branco/qtde}')



